services:
  - type: web
    runtime: docker
    name: fleet
    repo: https://github.com/fleetdm/fleet.git
    numInstances: 1
    branch: main
    buildCommand: 'make deps && make build && make'
    preDeployCommand: 'build/fleet prepare db'
    envVars:
      - key: FLEET_SERVER_ADDRESS
        value: '0.0.0.0:8080'
      - key: FLEET_MYSQL_ADDRESS
        fromDatabase:
          name: fleet-database
          property: connectionString
      - key: FLEET_REDIS_ADDRESS
        fromService:
          type: redis
          name: fleet-redis
          property: connectionString
    healthCheckPath: '/healthz'
  - type: redis
    name: fleet-redis
    plan: free
    ipAllowList: # Required
      - source: 0.0.0.0/0
        description: everywhere
databases:
  - name: fleet-database
    plan: free
    databaseName: fleetdb
    user: fleetuser
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere