openapi: 3.1.0
info:
  title: Setup Experience API
  version: 1.0.0
  description: The setup experience API.
paths:
  # TLDR This is a copy of list titles w/ new included_during_setup field and hardcoded
  # to filter on macOS custom packages only
  /api/v1/fleet/setup_experience/software:
    get:
      summary: Get a list of software available in the setup experience fleet
      parameters:
        - name: page
          in: query
          required: false
          description: The page number to return.
          schema:
            type: integer
        - name: per_page
          in: query
          required: false
          description: The number of results per page.
          schema:
            type: integer
        - name: team_id
          in: query
          required: false
          description: The team id to filter by.
          schema:
            type: integer
      responses:
        '200':
          description: A list of software available in the setup experience fleet
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: The total number of software available.
                  counts_updated_at:
                    type: string
                    description: The last time the counts were updated.
                  meta:
                    type: object
                    properties:
                      has_next_results:
                        type: boolean
                      has_previous_results:
                        type: boolean
                  software_titles:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        versions_count:
                          type: integer
                        source:
                          type: string
                        browser:
                          type: string
                        hosts_count:
                          type: integer
                        installed_during_setup:
                          type: boolean
                        versions:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: integer
                              version:
                                type: string
                              vulnerabilities:
                                type: array
                                items: string
                        software_package:
                          type: object
                          nullable: true
                          properties:
                            name:
                              type: string
                            version:
                              type: string
                            self_service:
                              type: boolean
                        app_store_app:
                          type: object
                          nullable: true
                          properties:
                            app_store_id:
                              type: integer
                            version:
                              type: string
    put:
      # Important: This endpoint must unset any software that is not included in the request
      summary: Update the list of software available in the setup experience fleet.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                description: software id's to enable.
            example: [1, 2, 3]
      responses:
        '200':
  /api/v1/fleet/setup_experience/script:
    get:
     summary: Get the script associated with this teams setup experience.
     responses:
       '200':
         description: The script associated with this teams setup experience.
         content:
           application/json:
             schema:
               type: object
               properties:
                 id:
                   type: integer
                 team_id:
                   type: integer
                 name:
                   type: string
                 created_at:
                   type: string
                 updated_at:
                   type: string
    delete:
      summary: Delete the script associated with this teams setup experience.
      responses:
        '200':
    post:
      summary: Update the script associated with this teams setup experience.
      requestBody:
        content:
          form-data:
            schema:
              type: object
              properties:
                team_id:
                  type: integer
                filename:
                  type: string
                script:
                  type: application/octet-stream
      responses:
        '200':
  /api/v1/fleet/{device_token}/setup_experience/start:
    post:
      summary: Register a device with the setup experience fleet.
      parameters:
        - name: device_token
          in: path
          required: true
          description: The device token to trigger the setup experience process.
          schema:
            type: string
      responses:
        '201':
  /api/v1/fleet/{device_token}/setup_experience/status:
    get:
      summary: Get the status of a device in the setup experience fleet.
      parameters:
        - name: device_token
          in: path
          required: true
          description: The device token to check the status of.
          schema:
            type: string
      responses:
        '200':
          description: The status of the device in the setup experience fleet.
          content:
            application/json:
              schema:
                type: object
                properties:
                  bootstrap_package:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                  script:
                    type: object
                    properties:
                      execution_id:
                        type: string
                      name:
                        type: string
                      status:
                        type: string
                  software:
                    type: array
                    items:
                      type: object
                      properties:
                        software_id:
                          type: integer
                        name:
                          type: string
                        status:
                          type: string