services:
  - type: web
    runtime: go
    name: fleet
    repo: https://github.com/fleetdm/fleet.git
    numInstances: 1
    branch: main
    buildCommand: 'make build'
    preDeployCommand: 'build/fleet prepare db'
    startCommand: 'build/fleet serve'
    envVars:
      - key: FLEET_SERVER_ADDRESS
        value: '0.0.0.0:8080'
      - key: FLEET_MYSQL_ADDRESS
        fromDatabase:
          name: fleet-database
          property: connectionString
      - key: FLEET_REDIS_ADDRESS
        fromService:
          type: redis
          name: fleet-redis
          property: connectionString
    healthCheckPath: '/healthz'

  - type: redis
    name: fleet-redis
    ipAllowList: # Required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # Default: starter

# List all PostgreSQL databases here
databases:

  # A database with a read replica
  - name: fleet-database
    databaseName: fleetdb # (Render may add a suffix)
    user: fleetuser 
    ipAllowList: # Optional (defaults to allow all)
      - source: 0.0.0.0/0
        description: everywhere