name: Test Windows code signing

on:
  pull_request:

jobs:
  build-windows-exe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-windows
          path: victor/hello-world.exe

  code-sign-windows:
    needs: build-windows-exe
    uses: ./.github/workflows/code-sign-windows.yml
    with:
      filename: hello-world.exe
    secrets:
      DIGICERT_KEYLOCKER_CERTIFICATE: ${{ secrets.DIGICERT_KEYLOCKER_CERTIFICATE }}
      DIGICERT_KEYLOCKER_PASSWORD: ${{ secrets.DIGICERT_KEYLOCKER_PASSWORD }}
      DIGICERT_KEYLOCKER_HOST_URL: ${{ secrets.DIGICERT_KEYLOCKER_HOST_URL }}
      DIGICERT_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
      DIGICERT_KEYLOCKER_CERTIFICATE_FINGERPRINT: ${{ secrets.DIGICERT_KEYLOCKER_CERTIFICATE_FINGERPRINT }}

  upload:
    needs: code-sign-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download signed artifact
        uses: actions/download-artifact@v4
        with:
          name: signed-windows

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world.exe
          path: hello-world.exe
